[profile.default]
solc = "0.8.15"
bytecode_hash = "none"
optimizer_runs = 0

# optimizer_runs = 0
# fuzz_runs = 100_000
# eth_rpc_url = "${RPC_MUMBAI}"
# eth_rpc_url = "https://rpc.ankr.com/polygon_mumbai"
# private_key = "${PRIVATE_KEY}"
libraries = []

fs_permissions = [{ access = "read-write", path = "./" }]

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
rinkeby = "${RPC_RINKEBY}"
polygon = "${RPC_POLYGON}"

anvil = "${RPC_ANVIL}"
mumbai = "${RPC_MUMBAI}"
goerli = "${RPC_GOERLI}"

[etherscan]
mainnet = { key = "${ETHERSCAN_KEY}" }
rinkeby = { key = "${ETHERSCAN_KEY}" }
goerli = { key = "${ETHERSCAN_KEY}" }

polygon = { key = "${POLYGONSCAN_KEY}" }
mumbai = { key = "${POLYGONSCAN_KEY}" }

[profile.mumbai]
# eth_rpc_url = "${RPC_MUMBAI}"
eth_rpc_url = "https://rpc.ankr.com/polygon_mumbai"
