[profile.default]
solc = "0.8.15"
bytecode_hash = "none"
# optimizer_runs = 100_000
optimizer_runs = 0
# eth_rpc_url = "${RPC_MUMBAI}"
# eth_rpc_url = "https://rpc.ankr.com/polygon_mumbai"
# private_key = "${PRIVATE_KEY}"

[rpc_endpoints]
mumbai = "${RPC_MUMBAI}"

mainnet = "${RPC_MAINNET}"
rinkeby = "${RPC_RINKEBY}"
goerli = "${RPC_GOERLI}"

polygon = "${RPC_POLYGON}"

[etherscan]
mainnet = { key = "${ETHERSCAN_KEY}" }
rinkeby = { key = "${ETHERSCAN_KEY}" }
goerli = { key = "${ETHERSCAN_KEY}" }

polygon = { key = "${POLYGONSCAN_KEY}" }
mumbai = { key = "${POLYGONSCAN_KEY}" }

[profile.mumbai]
# eth_rpc_url = "${RPC_MUMBAI}"
eth_rpc_url = "https://rpc.ankr.com/polygon_mumbai"
